M48
; DRILL file {KiCad 8.0.8} date 2025-01-16T17:40:09+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-16T17:40:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X115.5Y-83.0
X115.5Y-132.0
X182.0Y-83.0
X182.0Y-132.0
M30
